site_name: pydase Documentation
repo_url: https://github.com/tiqi-group/pydase
edit_uri: blob/docs/docs/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Components Guide: user-guide/Components.md
    - Interacting with pydase Services: user-guide/interaction/main.md
    - Service Persistence: user-guide/Service_Persistence.md
  - Developer Guide: 
    - Developer Guide: dev-guide/README.md
    - API Reference: dev-guide/api.md
    - Adding Components: dev-guide/Adding_Components.md
    - Observer Pattern Implementation: dev-guide/Observer_Pattern_Implementation.md  # <-- New section
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

theme: 
  name: material
  features:
    - content.code.copy

extra_css:
  - css/extra.css

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite


plugins:
  - include-markdown
  - search
  - mkdocstrings
  - swagger-ui-tag

watch:
  - src/pydase
