site_name: pydase Documentation
repo_url: https://github.com/tiqi-group/pydase
edit_uri: blob/docs/docs/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide:
    - Components Guide: user-guide/Components.md
    - Interacting with pydase Services: user-guide/interaction/README.md
    - Achieving Service Persistence: user-guide/Service_Persistence.md
    - Understanding Tasks: user-guide/Tasks.md
    - Understanding Units: user-guide/Understanding-Units.md
    - Validating Property Setters: user-guide/Validating-Property-Setters.md
    - Configuring pydase: user-guide/Configuration.md
    - Advanced:
        - Deploying behind a Reverse Proxy: user-guide/advanced/Reverse-Proxy.md
  - Developer Guide: 
    - Developer Guide: dev-guide/README.md
    - API Reference: dev-guide/api.md
    - Adding Components: dev-guide/Adding_Components.md
    - Observer Pattern Implementation: dev-guide/Observer_Pattern_Implementation.md  # <-- New section
  - About:
    - Release Notes: about/release-notes.md
    - Contributing: about/contributing.md
    - License: about/license.md

theme: 
  name: material
  features:
    - content.code.copy

extra_css:
  - css/extra.css

markdown_extensions:
  - smarty
  - toc:
      permalink: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite


plugins:
- include-markdown
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]  # search packages in the src folder
        import:
          - https://docs.python.org/3/objects.inv
          - https://docs.pydantic.dev/latest/objects.inv
          - https://confz.readthedocs.io/en/latest/objects.inv
          - https://python-socketio.readthedocs.io/en/stable/objects.inv
        options:
          show_source: true
          inherited_members: true
          merge_init_into_class: true
          show_signature_annotations: true
          signature_crossrefs: true
          separate_signature: true
          docstring_options:
            ignore_init_summary: true
          # docstring_section_style: list
          heading_level: 2
          parameter_headings: true
          show_root_heading: true
          show_root_full_path: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          # summary: true
          unwrap_annotated: true
- swagger-ui-tag

watch:
  - src/pydase
